### ISSUE TITLE
Failed to resolve import "./cssParser.mjs" in astro-fonts

### ISSUE THREAD

**Issue by Tc-001** [aFuzzyBear/astro-ui#53]
`astro-fonts` from 2.0 forward will crash with the following error:

```
Failed to resolve import "./cssParser.mjs" from "node_modules/astro-fonts/Fonts.astro". Does the file exist?

Error: Failed to resolve import "./cssParser.mjs" from "node_modules/astro-fonts/Fonts.astro". Does the file exist?
    at formatError (/sandbox/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:42212:46)
    at TransformContext.error (/sandbox/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:42208:19)
    at normalizeUrl (/sandbox/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:67278:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async TransformContext.transform (/sandbox/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:67418:57)
    at async Object.transform (/sandbox/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:42419:30)
    at async doTransform (/sandbox/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:56766:29)
```

This  seems to be because the published version does not include `cssParser.mjs`, as can be seen here: 
* https://www.jsdelivr.com/package/npm/astro-fonts?version=0.2.2 (not included)
* https://github.com/aFuzzyBear/astro-ui/tree/main/components/Fonts (expected)

CodeSandbox repro: https://codesandbox.io/s/staging-wind-8lmhcv?file=/src/pages/index.astro

P.S. Thanks for the awesome component! It has helped me finally ditch google's CDN for good

**Comment by aFuzzyBear** [comment]
Hi @Tc-001 I'll look into this after the rfc call tonight and hopefully have it resolved for you, likewise, the Google api is something @lostra01 worked hard to leverage, really happy with the outcome, just need tweaking and lots of user feedback,

**Comment by aFuzzyBear** [comment]
Hey @Tc-001 , I have added the cssParser to the package.json, hopefully that should correct this issue. 
My apologies for it this, thank you again for raising this with me. 
👊
